### ISSUE TITLE
Generic interface for final transformation - JSD/EMD, etc.

### ISSUE THREAD

**Issue by sdmccabe** [netsiphd/netrd#165] opened 2019-05-06 19:18 UTC
While our experimental pipeline can usually plug-and-play relatively well using `self.results`, we should consider making it more straightforward to do this, so that, e.g., we can consider if portrait divergence has different behavior using the EMD instead of the JSD.

**Comment by leotrs** [comment] 2019-05-13 18:25
Possible duplicate of #174 -- if anyone can confirm please close this

**Closed** 2019-05-15 13:51 UTC
Labels: help wanted
